//
// Generated file, do not edit! Created by opp_msgtool 6.0 from maxmin.msg.
//

#ifndef __MAXMIN_M_H
#define __MAXMIN_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class MaxMinMsg;
class ACKMsg;
/**
 * Class generated from <tt>maxmin.msg:12</tt> by opp_msgtool.
 * <pre>
 * message MaxMinMsg
 * {
 *     int msgId;
 *     int source;
 *     int destination;
 * }
 * </pre>
 */
class MaxMinMsg : public ::omnetpp::cMessage
{
  protected:
    int msgId = 0;
    int source = 0;
    int destination = 0;

  private:
    void copy(const MaxMinMsg& other);

  protected:
    bool operator==(const MaxMinMsg&) = delete;

  public:
    MaxMinMsg(const char *name=nullptr, short kind=0);
    MaxMinMsg(const MaxMinMsg& other);
    virtual ~MaxMinMsg();
    MaxMinMsg& operator=(const MaxMinMsg& other);
    virtual MaxMinMsg *dup() const override {return new MaxMinMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MaxMinMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MaxMinMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>maxmin.msg:19</tt> by opp_msgtool.
 * <pre>
 * message ACKMsg
 * {
 *     int msgId;
 *     int source;
 *     int destination;
 * }
 * </pre>
 */
class ACKMsg : public ::omnetpp::cMessage
{
  protected:
    int msgId = 0;
    int source = 0;
    int destination = 0;

  private:
    void copy(const ACKMsg& other);

  protected:
    bool operator==(const ACKMsg&) = delete;

  public:
    ACKMsg(const char *name=nullptr, short kind=0);
    ACKMsg(const ACKMsg& other);
    virtual ~ACKMsg();
    ACKMsg& operator=(const ACKMsg& other);
    virtual ACKMsg *dup() const override {return new ACKMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ACKMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ACKMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline MaxMinMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<MaxMinMsg*>(ptr.get<cObject>()); }
template<> inline ACKMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<ACKMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MAXMIN_M_H

